name: Deploy to DOM Cloud

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql, zip, pdo, pdo_mysql, pdo_pgsql, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: |
            {
              "features": [
                {
                  "create": {
                    "domain": "hospitaldewa.domcloud.dev",
                    "user": "hospitaldewa",
                    "pass": "<redacted>",
                    "email": "ramasyailana3@gmail.com"
                  }
                },
                "postgresql",
                "php latest",
                "ssl",
                "ssl always"
              ],
              "source": "https://github.com/MasDewaa/hospital-laravel12",
              "nginx": {
                "root": "public_html/public",
                "fastcgi": "on",
                "locations": [
                  {
                    "match": "/",
                    "try_files": "$uri $uri/ /index.php$is_args$args"
                  },
                  {
                    "match": "~ \\.[^\\/]+(?<!\\.php)$",
                    "try_files": "$uri =404"
                  }
                ]
              },
              "commands": [
                "(cp .env.example .env) || curl -sSLo .env https://raw.githubusercontent.com/laravel/laravel/refs/heads/12.x/.env.example",
                "sed -ri \"s/APP_URL=.*/APP_URL=https:\\/\\/${DOMAIN}/g\" .env",
                "sed -ri \"s/(# )?DB_CONNECTION=.*/DB_CONNECTION=pgsql/g\" .env",
                "sed -ri \"s/(# )?DB_HOST=.*/DB_HOST=localhost/g\" .env",
                "sed -ri \"s/(# )?DB_PORT=.*/DB_PORT=5432/g\" .env",
                "sed -ri \"s/(# )?DB_DATABASE=.*/DB_DATABASE=${DATABASE}/g\" .env",
                "sed -ri \"s/(# )?DB_USERNAME=.*/DB_USERNAME=${USERNAME}/g\" .env",
                "sed -ri \"s/(# )?DB_PASSWORD=.*/DB_PASSWORD=${PGPASSWD}/g\" .env",
                "sed -ri \"s/LOG_STACK=single/LOG_STACK=daily,errorlog/g\" .env",
                "sed -ri \"s/(# )?APP_DEBUG=.*/APP_DEBUG=false/g\" .env",
                "composer install --no-dev --optimize-autoloader",
                "php artisan migrate:fresh --seed || true",
                "php artisan key:generate",
                "php artisan storage:link",
                "php artisan config:cache",
                "php artisan route:cache",
                "php artisan view:cache",
                "chmod 0750 -R storage || true",
                "chmod 0755 -R bootstrap/cache || true",
                "rm -f public/hot"
              ],
              "wait": 1
            }
          verbose: true

      - name: Check deployment status
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploycheck
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}